Employee_details_webapp/Employee_details_webapp/Controllers/CombinedController.cs
using System;
using System.Reflection.Metadata;
using DomainLayer.Models;
using Employee_details_webapp.Models;
using FluentValidation;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ServiceLayer.Interfaces;
using ServiceLayer.Services;
using Microsoft.AspNetCore.Http.Features;
using System.Linq;
using System.Linq.Dynamic.Core;
using Npgsql.EntityFrameworkCore.PostgreSQL.Query.ExpressionTranslators.Internal;
using Employee_details_webapp.Models.Validators;

namespace Employee_details_webapp.Controllers
{
    public class CombinedController : Controller
    {

        private readonly IPositionService _positionService;
        private readonly IPeopleService _peopleService;
        private readonly IEmployeeService _employeeService;
        private readonly IEmployeeJobHistoryService _employeeJobHistoryService;

        public CombinedController(IPositionService positionService, IPeopleService peopleService, IEmployeeService employeeService,
            IEmployeeJobHistoryService employeeJobHistoryService)
        {
            _positionService = positionService;
            _peopleService = peopleService;
            _employeeService = employeeService;
            _employeeJobHistoryService = employeeJobHistoryService;
        }


        public IActionResult Index()
        {
            return View();
        }



        [HttpGet("Combined/AllEmployeesList")]
        public IActionResult AllEmployeesList()
        {
           return View();
        }



        [HttpPost("Combined/Combined/AllEmployeesList2")]
        public JsonResult AllEmployeesList2()
        {

            var employees = _employeeService.GetAllEmployees().ToList();
            var people = _peopleService.GetAllPeople().ToList();
            var positions = _positionService.GetAllPositions().ToList();

            List<CombinedViewModel> combinedViewModelList = new List<CombinedViewModel>();

            employees.ForEach(employee =>
            {
                if(employee.ISDisabled == false)
                {
                    People people = _peopleService.GetPeople(employee.Personid);
                    Positions position = _positionService.GetPosition(employee.Positionid);

                    CombinedViewModel combinedViewModel = new()
                    {
                        FirstName = people.FirstName,
                        MiddleName = people.MiddleName,
                        LastName = people.LastName,
                        FullName = people.FirstName + " " + people.MiddleName + " " + people.LastName,
                        Address = people.Address,
                        Email = people.Email,
                        Employeeid = employee.Employeeid,
                        EmployeeCode = employee.EmployeeCode,
                        Salary = employee.Salary,
                        StartDate = DateOnly.FromDateTime(employee.StartDate).ToString(),
                        EndDate = DateOnly.FromDateTime(employee.EndDate).ToString(),
                        ISDisabled = employee.ISDisabled,
                        PositionName = position.PositionName
                    };
                    combinedViewModelList.Add(combinedViewModel);
                }
                
            });
            var combinedViewModelList2 = combinedViewModelList.AsQueryable();

            var draw = Request.Form["draw"].FirstOrDefault();
            var start = Request.Form["start"].FirstOrDefault();
            var length = Request.Form["length"].FirstOrDefault();
            var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
            var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
            var searchValue = Request.Form["search[value]"].FirstOrDefault();
            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;
            int recordsTotal = combinedViewModelList.Count();
            int filteredRecords = 0;

            //search data when search value found
            /* if (!string.IsNullOrEmpty(searchValue))
            {
                combinedViewModelList.ForEach(x =>
                {
                    if (!(x.FirstName.ToLower().Contains(searchValue.ToLower())
                        || x.LastName.ToLower().Contains(searchValue.ToLower())
                        || x.Email.ToLower().Contains(searchValue.ToLower())
                        || x.Address.ToLower().Contains(searchValue.ToLower())
                        || x.Salary.ToString().ToLower().Contains(searchValue.ToLower())))
                    {
                        combinedViewModelList.Remove(x);
                    }
                });
            }*/

            //search data when search value found
            if (!string.IsNullOrEmpty(searchValue))
            {
                combinedViewModelList2 = combinedViewModelList2.Where(x =>
                  x.FirstName.ToLower().Contains(searchValue.ToLower())
                  || x.LastName.ToLower().Contains(searchValue.ToLower())
                  || x.FullName.ToLower().Contains(searchValue.ToLower())
                  || x.Email.ToLower().Contains(searchValue.ToLower())
                  || x.Address.ToLower().Contains(searchValue.ToLower())
                  || x.Salary.ToString().ToLower().Contains(searchValue.ToLower())
                  || x.PositionName.ToLower().Contains(searchValue.ToLower())
                  || x.StartDate.ToLower().Contains(searchValue.ToLower())
                );
            }

            //filtered data after search
            filteredRecords = combinedViewModelList2.Count();

            //sort data
            if (!string.IsNullOrEmpty(sortColumn) && !string.IsNullOrEmpty(sortColumnDirection))
                combinedViewModelList2 = combinedViewModelList2.OrderBy(sortColumn + " " + sortColumnDirection).AsQueryable();

            //pagination
            var empList = combinedViewModelList2.Skip(skip).Take(pageSize).ToList();

            var jsonData = new { draw = draw, recordsFiltered = filteredRecords, recordsTotal = recordsTotal, data = empList };
            // return Ok(jsonData);
            return Json(jsonData);
        }




        [HttpGet]
        public IActionResult AddEmployee()
        {
            ViewBag.positions = _positionService.GetAllPositions().ToList();

            //Sending suggested date for Start date and End dates
            AddViewModel addviewmodel = new()
            {
                StartDate = DateTime.Now,
                EndDate = DateTime.MaxValue
            };

            //Making list of email for dublicate email validation
            var peopleList = _peopleService.GetAllPeople().ToList();
            peopleList.ForEach(person =>
            {
                addviewmodel.EmailList.Add(person.Email);
            });
            return View(addviewmodel);
        }





        [HttpPost]
        public IActionResult AddEmployee(AddViewModel addRequest)
        {
            ViewBag.positions = _positionService.GetAllPositions().ToList();
            var people = new People()
            {
                Personid = Guid.NewGuid(),
                FirstName = addRequest.FirstName,
                MiddleName = addRequest.MiddleName,
                LastName = addRequest.LastName,
                Address = addRequest.Address,
                Email = addRequest.Email
            };
            var employee = new Employees()
            {
                Employeeid = Guid.NewGuid(),
                EmployeeCode = addRequest.EmployeeCode,
                StartDate = addRequest.StartDate,
                EndDate = addRequest.EndDate,
                Salary = addRequest.Salary,
                Personid = people.Personid,
                Positionid = addRequest.Positionid,
            };
            var employeeJobHistory = new EmployeeJobHistories()
            {
                EmployeeJobHistoryid = Guid.NewGuid(),
                Employeeid = employee.Employeeid,
                Positionid = addRequest.Positionid,
                StartDate = employee.StartDate,
                EndDate = employee.EndDate
            };

            addRequest.OriginalEmail = people.Email;

            //Making list of email for dublicate email validation
            var peopleList = _peopleService.GetAllPeople().ToList();
            peopleList.ForEach(person =>
            {
                addRequest.EmailList.Add(person.Email);
            });

            EmployeeValidator _validator = new();
            ValidationResult result = _validator.Validate(addRequest);

            if (result.IsValid)
            {
                _peopleService.InsertPeople(people);
                _employeeService.InsertEmployee(employee);
                _employeeJobHistoryService.InsertEmployeeJobHistory(employeeJobHistory);
                return RedirectToAction("AllEmployeesList");
            }
            else
            {
                //return BadRequest(result.Errors.Select(s => s.ErrorMessage).ToList());
                return View(addRequest);
            }
        }




        [HttpGet]
        public IActionResult EditEmployee(Guid Id)
        {
            var employee = _employeeService.GetEmployee(Id);
            var person = _peopleService.GetPeople(employee.Personid);
            var position = _positionService.GetPosition(employee.Positionid);

            ViewBag.positions = _positionService.GetAllPositions().ToList();

            var editViewModel = new EditViewModel()
            {
                Personid = employee.Personid,
                Employeeid = employee.Employeeid,
                Positionid = employee.Positionid,
                FirstName = person.FirstName,
                MiddleName = person.MiddleName,
                LastName = person.LastName,

Employee_details_webapp/Employee_details_webapp/Controllers/PositionController.cs
using DomainLayer.Models;
using Employee_details_webapp.Models;
using Microsoft.AspNetCore.Mvc;
using ServiceLayer.Interfaces;
using ServiceLayer.Services;

namespace Employee_details_webapp.Controllers
{
    public class PositionController : Controller
    {

        private readonly IPositionService _positionService;

        public PositionController(IPositionService positionService)
        {
            _positionService = positionService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AllPositionList()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AddPosition()
        {
            ViewBag.positions = _positionService.GetAllPositions().ToList();
            return View();
        }

        [HttpPost]
        public IActionResult AddPosition(PositionViewModel positionviewmodel)
        {

            if (positionviewmodel != null)
            {

                Positions positions = new()
                {
                    Positionid = Guid.NewGuid(),
                    PositionName = positionviewmodel.PositionName
                };

                _positionService.InsertPosition(positions);
                return RedirectToAction("AddPosition");
            }
            return RedirectToAction("AddPosition");
        }
    }
}

Employee_details_webapp/Employee_details_webapp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employee_details_webapp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Employee_details_webapp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Employee_details_webapp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Combined" asp-action="AddEmployee">Add Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Combined" asp-action="AllEmployeesList">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Position" asp-action="AddPosition">Positions</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Employee_details_webapp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#myTable2').DataTable();
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>